---

##############################################################
# Resource Types
##############################################################
resource_types:

- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource


##############################################################
# Resources
##############################################################
resources:

- name: gcs-kubo-deployment-tarball
  type: gcs
  source:
    json_key: ((gcp-json-key))
    bucket: kubo-public
    versioned_file: kubo-deployment-latest.tgz

- name: git-pfs-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/pfs-ci.git
    private_key: ((git-pfs-ci-ssh-key))
    branch: master

##############################################################
# Jobs
##############################################################
jobs:

- name: pave-infrastructure
  plan:

  - aggregate:
    - get: git-pfs-ci
    - get: gcs-kubo-deployment-tarball

  - task: unpack-tgz
    file: git-pfs-ci/tasks/unpack-tgz.yml
    input_mapping:
      source_tarball: kubo-deployment-tarball
    params:
      SOURCE_TARBALL_REGEX: kubo-deployment-*.tgz
      COLLAPSE_DIR: kubo-deployment

  - task: tf-apply
    file: git-pfs-ci/tasks/tf-invoke.yml
    input_mapping:
      tf-source-dir: unpacked_dir
    params:
      COMMAND: apply
      SERVICE_ACCOUNT_EMAIL: ((pfs-gcp-ci-service-account-email))
      ENV_PREFIX: pfsenv01
      PROJECT_ID: ((pfs-gcp-ci-project))
      NETWORK_NAME: pfsenv01net
      REGION: us-central1
      AZ: us-central1-c
      SUBNET_IP_PREFIX: 10.0.30
