resources:

- name: git-pfs-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/pfs-ci.git
    private_key: ((git-pfs-ci-ssh-key))
    branch: master

- name: faas_build_dockerimage
  type: docker-image
  source:
    repository: ((docker-sk8s-org))/faas-build
    username: ((docker-sk8s-username))
    password: ((docker-sk8s-password))

- name: faas_cli_build_dockerimage
  type: docker-image
  source:
    repository: ((docker-sk8s-org))/faas-cli-build
    username: ((docker-sk8s-username))
    password: ((docker-sk8s-password))

- name: faas_tf_dockerimage
  type: docker-image
  source:
    repository: ((docker-sk8s-org))/pfs-ci-tf
    username: ((docker-sk8s-username))
    password: ((docker-sk8s-password))


- name: faas_gcloud_dockerimage
  type: docker-image
  source:
    repository: ((docker-sk8s-org))/pfs-ci-gcloud
    username: ((docker-sk8s-username))
    password: ((docker-sk8s-password))


- name: fabric8_build_dockerimage
  type: docker-image
  source:
    repository: ((docker-sk8s-org))/fabric8_build
    username: ((docker-sk8s-username))
    password: ((docker-sk8s-password))

jobs:

- name: faas_build_dockerimage
  plan:
  - get: git-pfs-ci
  - put: faas_build_dockerimage
    params:
      build: git-pfs-ci/tasks/containers/faas_build

- name: faas_cli_build_dockerimage
  plan:
  - get: git-pfs-ci
  - put: faas_cli_build_dockerimage
    params:
      build: git-pfs-ci/tasks/containers/faas_cli_build

- name: faas_tf_dockerimage
  plan:
  - get: git-pfs-ci
  - put: faas_tf_dockerimage
    params:
      build: git-pfs-ci/tasks/containers/terraform_extended

- name: faas_gcloud_dockerimage
  plan:
  - get: git-pfs-ci
  - put: faas_gcloud_dockerimage
    params:
      build: git-pfs-ci/tasks/containers/gcloud_extended

- name: fabric8_build_dockerimage
  plan:
  - get: git-pfs-ci
  - put: fabric8_build_dockerimage
    params:
      build: git-pfs-ci/tasks/containers/fabric8_build
