<%
  DockerImage = Struct.new(:path, :name)
  sk8s_docker_images = [
    DockerImage.new('event-dispatcher', 'cfmobile/sk8s-event-dispatcher'),
    DockerImage.new('function-invokers/java-function-invoker','cfmobile/sk8s-java-function-invoker'),
    DockerImage.new('function-invokers/node-function-invoker','cfmobile/sk8s-node-function-invoker'),
    DockerImage.new('function-invokers/python2-function-invoker', 'cfmobile/sk8s-python2-function-invoker'),
    DockerImage.new('function-invokers/shell-function-invoker', 'cfmobile/sk8s-shell-function-invoker'),
    DockerImage.new('function-sidecar','cfmobile/sk8s-function-sidecar'),
    DockerImage.new('topic-controller','cfmobile/sk8s-topic-controller'),
    DockerImage.new('topic-gateway','cfmobile/sk8s-topic-gateway'),
    DockerImage.new('zipkin-server', 'cfmobile/sk8s-zipkin-server')
  ]

%>

resources:
- name: git-sk8s
  type: git
  source:
    uri: https://github.com/markfisher/sk8s
    base: master

- name: git-kubernetes-model
  type: git
  source:
    uri: https://github.com/ericbottard/kubernetes-model
    branch: sk8s

- name: git-pfs-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/pfs-ci.git
    private_key: ((git-pfs-ci-ssh-key))
    branch: master

- name: git-faas-cli
  type: git
  source:
    uri: git@github.com:pivotal-cf/faas-cli.git
    private_key: ((git-pfs-ci-ssh-key))
    branch: master

<% sk8s_docker_images.each do |image| %>
- name:  <%= image.name %>
  type: docker-image
  source:
    repository: <%= image.name %>
    username: ((docker-cfmobile-username))
    password: ((docker-cfmobile-password))
<% end %>

- name: gh-faas-cli-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: faas-cli
    access_token: ((gitbot-access-token))
    pre_release: true

jobs:
- name: build-faas-cli
  plan:
  - get: git-pfs-ci
  - get: git-faas-cli
  - task: build-faas-cli
    file: git-pfs-ci/tasks/build-faas-cli.yml
    privileged: true

  - put: git-faas-cli
    params:
      tag: faas-cli-out/release.tag
      only_tag: true
      force: true
      repository: git-faas-cli

  - put: gh-faas-cli-release
    params:
      name: faas-cli-out/release.name
      tag: faas-cli-out/release.tag
      globs:
      - faas-cli-out/faas-cli*

- name: build-sk8s
  plan:
  - get: git-pfs-ci
  - get: git-sk8s
  - get: git-kubernetes-model
    params:
      depth: 1

  - task: build-fabric8-model
    file: git-pfs-ci/tasks/build-fabric8-model.yml

  - task: build-sk8s
    file: git-pfs-ci/tasks/build-sk8s.yml
<% sk8s_docker_images.each do |image| %>
  - put:  <%= image.name %>
    params:
      build: sk8s-docker-contexts/<%= image.path %>
      build_args:
        JAR_FILE: '*.jar'
<% end %>

- name: deploy-sk8s
  plan:
  - get: git-pfs-ci
  - get: git-sk8s
    passed: [build-sk8s]
  - task: deploy-sk8s
    file: git-pfs-ci/tasks/deploy-sk8s.yml
    params:
      KUBECONFIG_STRING: ((pfs-gcp-kubeconfig-pfsenv01))
      K8S_NS_PREFIX: pfs-ci

- name: build-sample-function-containers-java
  plan:
  - get: gh-faas-cli-release
    passed: [build-faas-cli]
  - get: git-pfs-ci
  - task: build-sample-function-containers-java
    file: git-pfs-ci/tasks/build-sample-function-containers-java.yml
    privileged: true
    params:
      DOCKERHUB_USERNAME: ((docker-cfmobile-username))
      DOCKERHUB_PASSWORD: ((docker-cfmobile-password))
