resources:
- name: git-sk8s
  type: git
  source:
    uri: https://github.com/markfisher/sk8s
    base: master

- name: git-kubernetes-model
  type: git
  source:
    uri: https://github.com/ericbottard/kubernetes-model
    branch: sk8s

- name: git-pfs-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/pfs-ci.git
    private_key: ((git-pfs-ci-ssh-key))
    branch: master

- name: docker-invoker-java-base
  type: docker-image
  source:
    repository: cfmobile/pfs-invoker-java-base
    username: ((docker-cfmobile-username))
    password: ((docker-cfmobile-password))

jobs:
- name: build-sk8s-and-invoker-java
  plan:
  - get: git-pfs-ci
  - get: git-sk8s
  - get: git-kubernetes-model
    params:
      depth: 1

  - task: build-sk8s
    file: git-pfs-ci/tasks/build-sk8s.yml

  - task: build-invoker-java-base
    file: git-pfs-ci/tasks/build-invoker-java-base.yml

  - put:  docker-invoker-java-base
    params: {build: sk8s-invoker-build-context}

#
# - name: build-sample-function-containers-java
#   plan:
#   - get: git-pfs-ci
#   - get: git-sk8s
#   - get: git-kubernetes-model
#     params:
#       depth: 1
#   - task: build-sk8s
#     file: git-pfs-ci/tasks/build-sk8s.yml
