<%
slack_notification="""
  on_success:
    do:
    - put: slack-alert
      params:
        channel: '#pfs-ops'
        text: |
          $BUILD_PIPELINE_NAME : $BUILD_JOB_NAME Passed
          https://ci.faas.to.cf-app.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  on_failure:
    do:
    - put: slack-alert
      params:
        channel: '#pfs-ops'
        text: |
          $BUILD_PIPELINE_NAME : $BUILD_JOB_NAME Failed
          https://ci.faas.to.cf-app.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
"""

%>

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-hook-url))

- name: faas-cli-version
  type: semver
  source:
    driver: gcs
    bucket: pfs_versions
    key: faas_cli_version
    json_key: ((gcp-json-key))

- name: git-pfs-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/pfs-ci.git
    private_key: ((git-pfs-ci-ssh-key))
    branch: master

- name: git-faas-cli
  type: git
  source:
    uri: git@github.com:pivotal-cf/faas-cli.git
    private_key: ((git-pfs-ci-ssh-key))
    branch: master

- name: gh-faas-cli-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: faas-cli
    access_token: ((gitbot-access-token))
    pre_release: true

jobs:
- name: build-faas-cli
  plan:
  - aggregate:
    - get: git-pfs-ci
    - get: faas-cli-version
    - get: git-faas-cli
      trigger: true

  - task: build-faas-cli
    file: git-pfs-ci/tasks/build-faas-cli.yml
    privileged: true
    params:
      KUBECONFIG_STRING: ((pfs-gcp-kubeconfig-pfsenv01))

  - put: git-faas-cli
    params:
      tag: faas-cli-version/version
      only_tag: true
      force: true
      repository: git-faas-cli

  - put: gh-faas-cli-release
    params:
      name: faas-cli-version/version
      tag: faas-cli-version/version
      globs:
      - faas-cli-out/faas-cli*

  - put: git-faas-cli
    params:
      tag: faas-cli-version/version
      repository: git-faas-cli

  - put: faas-cli-version
    params: {bump: patch}

<%= slack_notification %>
