<%
  DockerImage = Struct.new(:path, :name)
  sk8s_docker_images = [
    DockerImage.new('event-dispatcher', 'sk8s/event-dispatcher'),
    DockerImage.new('function-invokers/java-function-invoker','sk8s/java-function-invoker'),
    DockerImage.new('function-invokers/node-function-invoker','sk8s/node-function-invoker'),
    #DockerImage.new('function-invokers/python2-function-invoker', 'sk8s/python2-function-invoker'),
    DockerImage.new('function-invokers/shell-function-invoker', 'sk8s/shell-function-invoker'),
    DockerImage.new('function-sidecar','sk8s/function-sidecar'),
    DockerImage.new('topic-controller','sk8s/topic-controller'),
    DockerImage.new('topic-gateway','sk8s/topic-gateway'),
    DockerImage.new('zipkin-server', 'sk8s/zipkin-server')
  ]

slack_notification="""
  on_success:
    do:
    - put: slack-alert
      params:
        channel: '#pfs-ops'
        text: |
          $BUILD_PIPELINE_NAME : $BUILD_JOB_NAME Passed
          https://ci.faas.to.cf-app.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  on_failure:
    do:
    - put: slack-alert
      params:
        channel: '#pfs-ops'
        text: |
          $BUILD_PIPELINE_NAME : $BUILD_JOB_NAME Failed
          https://ci.faas.to.cf-app.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
"""

%>

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:

- name: gcs-sk8s-charts
  type: gcs-resource
  source:
    bucket: sk8s_charts_dev
    json_key: ((gcp-json-key))
    regexp: sk8s*tgz

- name: gcs-sk8s-chart-index
  type: gcs-resource
  source:
    bucket: sk8s_charts_dev
    json_key: ((gcp-json-key))
    regexp: index.yaml

- name: sk8s-version
  type: semver
  source:
    driver: gcs
    bucket: pfs_versions
    key: sk8s_version
    json_key: ((gcp-json-key))

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-hook-url))

- name: git-go-sidecar
  type: git
  source:
    uri: https://github.com/pivotal-jamie-klassen/function-sidecar.git
    branch: tracing

- name: git-sk8s
  type: git
  source:
    uri: https://github.com/markfisher/sk8s
    branch: master

- name: git-kubernetes-model
  type: git
  source:
    uri: https://github.com/ericbottard/kubernetes-model
    branch: sk8s-sidecar-scaling

- name: git-pfs-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/pfs-ci.git
    private_key: ((git-pfs-ci-ssh-key))
    branch: master


- name: go_sidecar_docker_image
  type: docker-image
  source:
    repository: ((docker-sk8s-org))/function-sidecar-go
    username: ((docker-sk8s-username))
    password: ((docker-sk8s-password))

<% sk8s_docker_images.each do |image| %>
- name:  <%= image.name %>
  type: docker-image
  source:
    repository: <%= image.name %>
    username: ((docker-sk8s-username))
    password: ((docker-sk8s-password))
<% end %>

jobs:

- name: version-bump-patch
  plan:
  - put: sk8s-version
    params: {bump: patch, pre: SNAPSHOT}

- name: version-bump-final
  plan:
  - put: sk8s-version
    params: {bump: final}

- name: build-go-sidecar
  plan:
  - aggregate:
    - get: git-pfs-ci
    - get: git-go-sidecar
      trigger: true
    - get: sk8s-version

  - task: build-go-sidecar
    file: git-pfs-ci/tasks/build-go-sidecar.yml

  - put: go_sidecar_docker_image
    params:
      build: go-sidecar-docker-context
      tag: go-sidecar-docker-context/sk8s_version
      tag_as_latest: true

- name: build-sk8s
  plan:
  - aggregate:
    - get: git-pfs-ci
    - get: sk8s-version
    - get: git-sk8s
      trigger: true
    - get: git-kubernetes-model
      params:
        depth: 1

  # - put: sk8s-version
  #   params: {bump: patch, pre: SNAPSHOT}

  - task: build-fabric8-model
    file: git-pfs-ci/tasks/build-fabric8-model.yml

  - task: build-sk8s
    file: git-pfs-ci/tasks/build-sk8s.yml
<% sk8s_docker_images.each do |image| %>
  - put:  <%= image.name %>
    params:
      build: sk8s-docker-contexts/<%= image.path %>
      tag: sk8s-docker-contexts/sk8s_version
      tag_as_latest: true
      build_args:
        JAR_FILE: '*.jar'
<% end %>
<%= slack_notification %>

- name: deploy-sk8s
  plan:
  - aggregate:
    - get: git-pfs-ci
    - get: sk8s-version
    - get: git-sk8s
      trigger: true
      passed: [build-sk8s]
  - task: deploy-sk8s
    file: git-pfs-ci/tasks/deploy-sk8s.yml
    params:
      KUBECONFIG_STRING: ((pfs-gcp-kubeconfig-pfsenv01))
      K8S_NS_PREFIX: pfs-ci
  - put: gcs-sk8s-charts
    params:
      file: sk8s-charts/*.tgz
      predefined_acl: publicRead
  - put: gcs-sk8s-chart-index
    params:
      file: sk8s-charts/index.yaml
      predefined_acl: publicRead
<%= slack_notification %>
