platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/faas-cli-build

inputs:
- name: git-faas-cli
- name: git-pfs-ci

outputs:
- name: faas-cli-out

params:
  KUBECONFIG_STRING: replace-me

run:
  path: /bin/bash
  args:
  - -exc
  - |
    start_docker

    mkdir -p ~/.kube
    echo "$KUBECONFIG_STRING" > ~/.kube/config

    build_root="$PWD"
    mkdir -p "$GOPATH/src/github.com/pivotal-cf"
    cp -r "$build_root/git-faas-cli" "$GOPATH/src/github.com/pivotal-cf/faas-cli"

    cd "$GOPATH/src/github.com/pivotal-cf/faas-cli"

    ./build.sh
    cp ./faas-cli* "$build_root/faas-cli-out/"
    echo "faas-cli-pre-alpha" >  "$build_root/faas-cli-out/release.name"
    echo "dev-build" >  "$build_root/faas-cli-out/release.tag"
