platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: git-faas-cli
- name: git-pfs-ci

outputs:
- name: faas-cli-out

run:
  path: /bin/bash
  args:
  - -exc
  - |
    wget https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
    mv dep-linux-amd64 /usr/local/bin/dep
    chmod +x /usr/local/bin/dep
    git-faas-cli/build.sh
    cp git-faas-cli/faas-cli faas-cli-out/
