platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/docker-image-resource
inputs:
- name: gh-faas-cli-release
- name: git-pfs-ci

params:
  DOCKERHUB_USERNAME: replace-me
  DOCKERHUB_PASSWORD: replace-me

run:
  path: /bin/sh
  args:
  - -exc
  - |
    source /opt/resource/common.sh
    start_docker

    apk update
    apk add alpine-sdk bash wget git openjdk8 maven

    build_root="$PWD"

    chmod +x gh-faas-cli-release/faas-cli

    cd git-pfs-ci/integration/sample_functions/java/uppercase
    mvn clean package

    function_name="sample-uppercase"

    "$build_root/gh-faas-cli-release/faas-cli" -n "$function_name" build

    new_image_id=$(docker images "$function_name" --format="{{.ID}}")

    docker tag "$new_image_id" "cfmobile/faas-test-$function_name"

    docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"

    docker push "cfmobile/faas-test-$function_name"
