platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/java-build

inputs:
- name: function-controller-version
- name: git-function-controller
- name: git-kubernetes-model
- name: git-pfs-ci

outputs:
- name: docker-context

run:
  path: /bin/bash
  args:
  - -o
  - pipefail
  - -exc
  - |

    build_root=$(pwd)

    source "$build_root/git-pfs-ci/tasks/scripts/common.sh"
    RIFF_VERSION=$(determine_riff_version "$build_root/git-function-controller" "$build_root/function-controller-version")

    export GOPATH=$(go env GOPATH)

    mkdir -p "$GOPATH/src/github.com/fabric8io"
    cp -pr git-kubernetes-model/ "$GOPATH/src/github.com/fabric8io/kubernetes-model"

    pushd "$GOPATH/src/github.com/fabric8io/kubernetes-model/"
      make
    popd

    pushd "$build_root/git-function-controller/"

      ./mvnw clean package

      cp -pr ./function-controller/* "$build_root/docker-context/"

      echo "$RIFF_VERSION" > "$build_root/docker-context/docker_version"

    popd
