platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/faas-build

inputs:
- name: git-pfs-ci
- name: git-node-function-invoker

outputs:
- name: docker-context

run:
  path: /bin/bash
  args:
  - -o
  - pipefail
  - -exc
  - |

    build_root=$(pwd)

    source "$build_root/git-pfs-ci/tasks/scripts/common.sh"
    SK8S_VERSION=$(determine_sk8s_version "$build_root/git-node-function-invoker" "$build_root/sk8s-version")

    pushd "$build_root/git-node-function-invoker"

      cp -pr . "$build_root/docker-context/"

      echo "$SK8S_VERSION" > "$build_root/docker-context/sk8s_version"

    popd
