platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: git-faas-cli
- name: git-pfs-ci

outputs:
- name: faas-cli-out

run:
  path: /bin/bash
  args:
  - -exc
  - |
    git-faas-cli/build.sh
    cp git-faas-cli/faas-cli faas-cli-out/
