platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/faas-build

inputs:
- name: git-sk8s
- name: git-pfs-ci
- name: sk8s-version

- name: sidecar-version
- name: topic-controller-version
- name: http-gateway-version

outputs:
- name: sk8s-charts

run:
  path: git-pfs-ci/tasks/scripts/build_sk8s_chart.sh

params:
  SK8S_CHARTS_URL: replace-me
