platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/kafka-zookeeper

inputs:
- name: function-sidecar-version
- name: git-function-sidecar
- name: git-pfs-ci

outputs:
- name: docker-context

run:
  path: /bin/bash
  args:
  - -o
  - pipefail
  - -exc
  - |

    start_kafka

    build_root=$(pwd)

    source "$build_root/git-pfs-ci/tasks/scripts/common.sh"
    SK8S_VERSION=$(determine_sk8s_version "$build_root/git-function-sidecar" "$build_root/function-sidecar-version")

    export GOPATH=$(go env GOPATH)

    mkdir -p "$GOPATH/src/github.com/projectriff"
    cp -pr git-function-sidecar "$GOPATH/src/github.com/projectriff/function-sidecar"

    killjava() {
        set +e
        pkill -9 java
        set -e
    }
    trap killjava INT QUIT TERM EXIT

    pushd "$GOPATH/src/github.com/projectriff/function-sidecar/"

      KAFKA_BROKER=localhost:9092 make clean test

      make build-for-docker

      killjava

      cp -pr . "$build_root/docker-context/"

      echo "$SK8S_VERSION" > "$build_root/docker-context/sk8s_version"

    popd
