platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/kafka-zookeeper

inputs:
- name: git-go-sidecar
- name: git-pfs-ci
- name: sk8s-version

outputs:
- name: go-sidecar-docker-context

run:
  path: /bin/bash
  args:
  - -o
  - pipefail
  - -exc
  - |
    start_kafka

    build_root=$(pwd)


    pushd git-go-sidecar

      make build

      GOPATH=$(go env GOPATH) KAFKA_BROKER=localhost:9092 go test -v cmd/function-sidecar_test.go

      cp -r ./* "$build_root/go-sidecar-docker-context/"

    popd
