platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/docker-image-resource
inputs:
- name: gh-faas-cli-release
- name: git-pfs-ci

run:
  path: /bin/sh
  args:
  - -exc
  - |
    source /opt/resource/common.sh
    start_docker

    apk update
    apk add alpine-sdk bash wget git openjdk8 maven

    build_root="$PWD"

    chmod +x gh-faas-cli-release/faas-cli

    cd git-pfs-ci/integration/sample_functions/java/uppercase
    mvn clean package

    "$build_root/gh-faas-cli-release/faas-cli" -n sample-uppercase build
