platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfmobile/faas-build

inputs:
- name: git-sk8s
- name: git-pfs-ci
- name: m2-repo

outputs:
- name: sk8s-docker-contexts

run:
  path: git-pfs-ci/tasks/scripts/build_sk8s.sh
