platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: git-faas-cli
- name: git-pfs-ci

outputs:
- name: faas-cli-out

run:
  path: /bin/bash
  args:
  - -exc
  - |
    wget https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64

    build_root="$PWD"

    go get github.com/maxbrunsfeld/counterfeiter

    mv dep-linux-amd64 /usr/local/bin/dep
    chmod +x /usr/local/bin/dep

    mkdir -p "$GOPATH/src/github.com/pivotal-cf"
    cp -r git-faas-cli "$GOPATH/src/github.com/pivotal-cf/faas-cli"

    cd "$GOPATH/src/github.com/pivotal-cf/faas-cli"

    ./build.sh
    cp ./faas-cli "$build_root/faas-cli-out/"
