platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/faas-build

inputs:
- name: git-pfs-ci
- name: git-sk8s
- name: sk8s-version

run:
  path: git-pfs-ci/tasks/scripts/clean_sk8s_deployment.sh

params:
  KUBECONFIG_STRING: replace-me
  K8S_NS_PREFIX: replace-me
