platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/faas-build

inputs:
- name: git-pfs-ci
- name: gcs-riff-chart-latest-version

run:
  path: git-pfs-ci/tasks/scripts/clean_riff_deployment.sh

params:
  KUBECONFIG_STRING: replace-me
  KUBECONFIG_CERT: replace-me
  KUBECONFIG_KEY: replace-me
