platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/faas-build

inputs:
- name: git-sk8s
- name: git-pfs-ci

run:
  path: git-pfs-ci/tasks/scripts/deploy_sk8s.sh

params:
  KUBECONFIG_STRING: replace-me
  K8S_NS_PREFIX: replace-me
