platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8sci/test-minikube

inputs:
- name: git-riff
- name: git-pfs-ci
- name: git-pfs-system-test
- name: gcs-riff-chart-latest-version
- name: java-function-invoker-version

run:
  path: /bin/bash
  args:
  - -o
  - pipefail
  - -exc
  - |
    add-apt-repository -y ppa:openjdk-r/ppa
    apt-get update
    apt-get install -y openjdk-8-jdk maven jq socat

    wget https://github.com/Dreyer/nsenter/releases/download/2.25.226-42f0/nsenter.tar.gz
    tar -xzf nsenter.tar.gz
    mv 2.25.226-42f0/bin/nsenter /usr/local/bin/

    export GOROOT=/usr/local/go
    export GOPATH=/root/go
    export PATH=$GOROOT/bin:$PATH
    wget https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz
    tar -C /usr/local -xzf go1.9.linux-amd64.tar.gz

    wget https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
    mv dep-linux-amd64 /usr/local/bin/dep
    chmod +x /usr/local/bin/dep

    curl -sL https://raw.githubusercontent.com/concourse/docker-image-resource/master/assets/common.sh > common.sh
    source common.sh
    start_docker
    minikube start
    stop_minikube() {
      set +e
      killall -9 docker
      killall -9 dockerd
      killall -9 minikube
    }
    trap stop_minikube EXIT

    set +e
    for i in {1..50}; do
       kubectl get po &> /dev/null
       if [ $? -ne 1 ]; then
          break
      fi
      sleep 2
    done
    set -e

    curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash

    git-pfs-ci/tasks/scripts/deploy_riff.sh
    git-pfs-ci/tasks/scripts/run_riff_system_tests.sh

params:
  KUBECONFIG_STRING: ""
  HELM_CHARTS_URL: replace-me
  DOCKER_TEST_ORG: replace-me
  DOCKER_USERNAME: replace-me
  DOCKER_PASSWORD: replace-me
