platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/faas-build

inputs:
- name: git-pfs-ci
- name: sk8s-version

outputs:
- name: sk8s-charts

run:
  path: git-pfs-ci/tasks/scripts/deploy_sk8s.sh

params:
  KUBECONFIG_STRING: replace-me
  K8S_NS_PREFIX: replace-me
  SK8S_CHARTS_URL: replace-me
