platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/faas-build

inputs:
- name: git-pfs-ci
- name: git-sk8s
- name: sk8s-version

run:
  path: git-pfs-ci/tasks/scripts/deploy_sk8s.sh

params:
  KUBECONFIG_STRING: replace-me
  SK8S_CHARTS_URL: replace-me
