platform: linux
image_resource:
  type: docker-image
  source:
    repository: whindes/alpine-minikube
    tag: 22.3

inputs:
- name: git-pfs-ci
- name: git-pfs-system-test
- name: git-sk8s
- name: sk8s-version

run:
  path: /bin/bash
  args:
  - -o
  - pipefail
  - -exc
  - |
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
    apk update
    apk add alpine-sdk git curl openssl jq socat util-linux wget go openjdk8

    wget https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
    mv dep-linux-amd64 /usr/local/bin/dep
    chmod +x /usr/local/bin/dep

    curl -sL https://raw.githubusercontent.com/concourse/docker-image-resource/master/assets/common.sh > common.sh
    source common.sh
    start_docker
    minikube start
    stop_minikube() {
      set +e
      killall -9 docker
      killall -9 dockerd
      killall -9 minikube
    }
    trap stop_minikube EXIT

    set +e
    for i in {1..50}; do
       kubectl get po &> /dev/null
       if [ $? -ne 1 ]; then
          break
      fi
      sleep 2
    done
    set -e

    curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash

    git-pfs-ci/tasks/scripts/deploy_sk8s.sh
    git-pfs-ci/tasks/scripts/run_sk8s_system_tests.sh

params:
  KUBECONFIG_STRING: ""
  SK8S_CHARTS_URL: replace-me
  DOCKER_ORG: replace-me
  DOCKER_USERNAME: replace-me
  DOCKER_PASSWORD: replace-me
