platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/faas-build

inputs:
- name: git-component-working-copy
- name: git-pfs-ci
- name: component-version

outputs:
- name: version-to-tag-git

params:
  SK8S_COMPONENT_GIT_REMOTE: replace-me

run:
  path: /bin/bash
  args:
  - -o
  - pipefail
  - -exc
  - |
    build_root=$(pwd)

    source "$build_root/git-pfs-ci/tasks/scripts/common.sh"
    CURRENT_VERSION=$(head "$build_root/component-version/version")
    RELEASE_VERSION=$(strip_snapshot_from_version $CURRENT_VERSION)

    echo "Release component [$SK8S_COMPONENT_GIT_REMOTE], version [$COMPONENT_VERSION]"

    echo "$RELEASE_VERSION" > "$build_root/version-to-tag-git/version"
