platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/faas-build

inputs:
- name: git-component-working-copy
- name: git-pfs-ci
- name: component-version

params:
  SK8S_COMPONENT_GIT_REMOTE: replace-me

run:
  path: /bin/bash
  args:
  - -o
  - pipefail
  - -exc
  - |
    build_root=$(pwd)

    source "$build_root/git-pfs-ci/tasks/scripts/common.sh"
    COMPONENT_VERSION=$(head "$build_root/component-version/version")

    echo "Release component [$SK8S_COMPONENT_GIT_REMOTE], version [$COMPONENT_VERSION]"
