platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/faas-build

inputs:
- name: git-pfs-ci

run:
  path: /bin/bash
  args:
  - -exc
  - |
    echo "Acceptance Tests for sk8s"
