platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/faas-cli-build

inputs:
- name: git-pfs-ci
- name: git-pfs-system-test
- name: git-sk8s
- name: sk8s-version

run:
  path: git-pfs-ci/tasks/scripts/run_sk8s_system_tests.sh
  
params:
  KUBECONFIG_STRING: replace-me
  DOCKER_ORG: replace-me
  DOCKER_USERNAME: replace-me
  DOCKER_PASSWORD: replace-me
