platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/faas-build

inputs:
- name: git-pfs-ci
- name: git-helm-charts

params:
  KUBECONFIG_STRING: replace-me
  KUBECONFIG_CERT: replace-me
  KUBECONFIG_KEY: replace-me

run:
  path: git-pfs-ci/tasks/custom-resource-defintion/publish/run
