platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/docker-image-resource

inputs:
- name: git-pfs-ci
- name: source-semver

params:
  DOCKERHUB_PASSWORD: replace-me
  DOCKERHUB_USERNAME: replace-me
  DOCKERHUB_ORG_SOURCE: replace-me
  DOCKERHUB_ORG_TARGET: replace-me
  DOCKER_IMAGE: replace-me

run:
  path: git-pfs-ci/tasks/release-management/docker-image-tagging/task.yml
