---
name: pfs-gcp-concourse

releases:
- name: concourse
  version: 3.5.0
- name: garden-runc
  version: 1.6.0

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: web
  instances: 1
  vm_type: medium-https

  stemcell: trusty
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: atc
    release: concourse
    properties:

      external_url: https://ci.faas.to.cf-app.com
      basic_auth_username: faasci
      basic_auth_password: ((atc_basic_auth_password))
      tls_cert: ((atc_cert.certificate))
      tls_key: ((atc_cert.private_key))
      postgresql_database: &atc_db atc
      tls_bind_port: 443
  - name: tsa
    release: concourse
    properties: {}

- name: db
  instances: 1
  vm_type: medium
  stemcell: trusty
  persistent_disk_type: default
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: *atc_db
        role: ((ci_db_role))
        password: ((ci_db_password))

- name: worker
  instances: 2
  vm_type: large

  stemcell: trusty
  azs: [z1]
  networks: [{name: default}]
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

variables:
- name: ci_db_password
  type: password
- name: atc_basic_auth_password
  type: password
- name: ci_db_role
  type: password
- name: atc_cert
  type: certificate
  options:
    is_ca: true
    common_name: ci.faas.to.cf-app.com
