platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/faas-build

inputs:
- name: git-pfs-ci
- name: gcs-riff-chart-latest-version
- name: gcs-riff-chart-latest-name

run:
  path: git-pfs-ci/task/riff-deployment/clean/run

params:
  KUBECONFIG_STRING: replace-me
  KUBECONFIG_CERT: replace-me
  KUBECONFIG_KEY: replace-me
